language: node_js
node_js:
- '7'
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.23.2
- export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
script:
- yarn travis
notifications:
  slack:
    secure: VCftv871cMff1ltPJiH4dG29Ge2tiibLQ+sR+KS9vHdOqP1f/BujDGXNy2IJ6i7MKQ9shlDgB/pTE9fDFJQ59c91SD/7YFyVTQVTbNl/LjMdVdFObw8VVmx6YJNA6RDRdopA5TL08lHlP0sKrpLI4xquuzopV6pEJbue8+jNTWs/8aViYZam4OWdO75swHumkwLQgjvHbDU6UIf0kCXgeREKS0cusZmdiMFym+5TN8WV3TZC/mZ24FjXAPgr8iYf5AxrRBUg6Uhp+t/ouon5z7e8wgeXsvrKv/oQmJX24+36SOXNjazod89JuDvKntm5ax6a1wJzxiRAtxmceZPPrUAkH342rmvqj+cB1+puqqp8g5YVHD9Hn53Yl0tDyNvQ81/IEU63DDljkZ+q3K3XLZoOhPO+JUfYRdWGu7B9RovFe5I5tmmSC9zBO1IAGSm/pGWtJFENyqZ7YajjIR+fUjAziMZgATS5W/Ork75tVd3nwZjKOXf60A1syGyPL7JFdX9lYUoBcvN60R9ulv2rzMJ5jr7te6LuQUP0MgWguuVGRFoueotCiD5sCI01M7+IjXOzuczyyeRSdBnWizUxRd3TtXwlNXBEZXmX9zWnRdOvtnUxKbk7GMlf0M791iwYfI8vqlJbcQKyH2iizOE0gkol9uZ6y4HAhmzgQOK/+4M=
deploy:
  provider: firebase
  token:
    secure: jIL43OszUVJKwaUMmQgc4p57DaPxepvaO0+EOpLjAv51nBMG+0+32CXoTSpTQHDzbfwbGy2y+Gi8fCMJa9eXkSLb/F4n4D1IxOAraeikvB+A2KGBZsh1XNJSf85BjsMX1/4DP0aieQY08q+qPc4c5e9CspWIW9rDL8qX6JvxNB9DcMr5+WgIl3d+KD0dmY87xD7KEdN73yY9SM6H3aofvFuA4o9yqJVUsan6a0gA8WqxCNb4Tp0ED6ise8rw4T1Woj5WMCAeoJtGI4Q5/ZfhCYWz4AgxL5BOg3xL99WDPx6kK6zNToT+AGOrExE9CzGe8KDJjUxyOdZQH27sz1ba88Xoj/nJWD9I/MIUSypngR6KScX6dnIdCi4B15TFUPxRddZSL7dbKUPfryBo1Sd3zWZm6/Zag7YARLFPV3nDPoUj8q7XdArMt79TnNu5VqUH8c0V6OBoBOpKU5pX5tiWc8iBOMB9qlC5ILvDsP/Xm/lLK6mVW313a9Q08ZIoN/C7pPWk+p7mVs/zawSE5KfQK0SN4pE4JCIMT3S534tsJzOsXwMvrPtrrX2h2aZJnyn9BDNu/qHXgO42Rn9TdENASQfb1mTRgYkVQjfVlh11gjEOQq1moLd2OoJH2OpVv4qDBEj6HaHPLyzRy9gcViMSSgRNJRR78b88BO6houoEIhc=
    project: "reactUltimate"
