language: node_js
node_js:
- '7'
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.23.2
- export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
script:
- yarn travis
notifications:
  slack:
    secure: VCftv871cMff1ltPJiH4dG29Ge2tiibLQ+sR+KS9vHdOqP1f/BujDGXNy2IJ6i7MKQ9shlDgB/pTE9fDFJQ59c91SD/7YFyVTQVTbNl/LjMdVdFObw8VVmx6YJNA6RDRdopA5TL08lHlP0sKrpLI4xquuzopV6pEJbue8+jNTWs/8aViYZam4OWdO75swHumkwLQgjvHbDU6UIf0kCXgeREKS0cusZmdiMFym+5TN8WV3TZC/mZ24FjXAPgr8iYf5AxrRBUg6Uhp+t/ouon5z7e8wgeXsvrKv/oQmJX24+36SOXNjazod89JuDvKntm5ax6a1wJzxiRAtxmceZPPrUAkH342rmvqj+cB1+puqqp8g5YVHD9Hn53Yl0tDyNvQ81/IEU63DDljkZ+q3K3XLZoOhPO+JUfYRdWGu7B9RovFe5I5tmmSC9zBO1IAGSm/pGWtJFENyqZ7YajjIR+fUjAziMZgATS5W/Ork75tVd3nwZjKOXf60A1syGyPL7JFdX9lYUoBcvN60R9ulv2rzMJ5jr7te6LuQUP0MgWguuVGRFoueotCiD5sCI01M7+IjXOzuczyyeRSdBnWizUxRd3TtXwlNXBEZXmX9zWnRdOvtnUxKbk7GMlf0M791iwYfI8vqlJbcQKyH2iizOE0gkol9uZ6y4HAhmzgQOK/+4M=
deploy:
  provider: firebase
  token:
    secure: Pf4H+IrQvJpifnAe0Sjg6ysz8qh1ZnjOoA48LA/w8PigvNtsbfTfxZVOF7cwGNW5Qb6uX5w8mhlD1aR4q2aALPsuylifO7PL3oe55U7rPS07EKhJMCqaDq576EEox5rO/d0ZtK/bECwtdE3QdCOO7n77Zgtqb7Z+I5VJganY4pXDD6duelnfhMXrRX5MxGnH8Hhx6qLUnvispU6c5AXTuxFIxrNYbOVn1ADCZl46HDMOvJR8IekLB29+8CUBNpMGzbEYcY8Ry5hq21WsRT+/tKQ/FJwQWZ3+jMMTF4KX0Z7zsIfNjnthw8C8pVROSlgIWmXVMe4WWsVUQ4EwosQdD8aifVblbVexmwP1JhLAM8vMjFPP676kCcYDGv9tPpfNLmALmG6BRCGpXk1MEWHNX2U/IT9bSTnAR3Nj62LsH3U601Yj3BFST9h0KwXWWZvynOUCF09b7+nDOjGJnnwt21MaGkNDFhyxGk37fUR/qpxTMpJkU9XvjOffhm+w26OcUmXnOtYycDcp05VW8XCOryu1CfY01kVdtGxqalcfXLfEJ3tiBLgF24ih1cRdOrTm+IZb6qcfhXyAokxqHFwIzD8yLo5/+MYL4FGwr6VYvnNuEZQwewIGWw7gvAP4jdqT9cUcHoPtkepD6kz1pTXZPHk2oGt3CZ2TQ8gQTmvZlaE=
    project: reactUltimate
env:
  global:
    secure: Pf4H+IrQvJpifnAe0Sjg6ysz8qh1ZnjOoA48LA/w8PigvNtsbfTfxZVOF7cwGNW5Qb6uX5w8mhlD1aR4q2aALPsuylifO7PL3oe55U7rPS07EKhJMCqaDq576EEox5rO/d0ZtK/bECwtdE3QdCOO7n77Zgtqb7Z+I5VJganY4pXDD6duelnfhMXrRX5MxGnH8Hhx6qLUnvispU6c5AXTuxFIxrNYbOVn1ADCZl46HDMOvJR8IekLB29+8CUBNpMGzbEYcY8Ry5hq21WsRT+/tKQ/FJwQWZ3+jMMTF4KX0Z7zsIfNjnthw8C8pVROSlgIWmXVMe4WWsVUQ4EwosQdD8aifVblbVexmwP1JhLAM8vMjFPP676kCcYDGv9tPpfNLmALmG6BRCGpXk1MEWHNX2U/IT9bSTnAR3Nj62LsH3U601Yj3BFST9h0KwXWWZvynOUCF09b7+nDOjGJnnwt21MaGkNDFhyxGk37fUR/qpxTMpJkU9XvjOffhm+w26OcUmXnOtYycDcp05VW8XCOryu1CfY01kVdtGxqalcfXLfEJ3tiBLgF24ih1cRdOrTm+IZb6qcfhXyAokxqHFwIzD8yLo5/+MYL4FGwr6VYvnNuEZQwewIGWw7gvAP4jdqT9cUcHoPtkepD6kz1pTXZPHk2oGt3CZ2TQ8gQTmvZlaE=
