const wordType = 'number';

module.exports = {
  entry: './index.js',
  dist: './.dist',
  prod: './.prod',
  bundle: 'bundle.js',
  port: process.env.PORT || 5000,
  devPort: 4000,
  devPublicPath: '/',
  prodPublicPath: '/',
  karma_files:['./src/**/*.test.js'],
  karma_preprocessors: ['webpack'],
  karma_browsers: ['PhantomJS'],
  karma_coverage_dir: '.coverage/',
  wordType,
  numOfLetters: 3,
  gameUrl: 'https://bullsncows-3d0f8.firebaseapp.com/',
  gameDescription: 'Discover the hidden '+wordType+'! Solve 2 and share your average. A popular game where you try to guess the '+wordType+' using the clues generated by the previous guess. Find out how many you can crack.'
};
